// 389. Find the Difference

/*
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

// HashTable
// Bit manipulate

class Solution {
public:
  char findTheDifference(string s, string t) {
    unordered_map<char, int> m;
    for (const auto& ch : s) {
      if (m.find(ch) == m.end()) {
        m[ch] = 1;
      } else {
        m[ch] += 1;
      }
    }
    
    for (const auto& ch : t) {
      if (m.find(ch) == m.end()) {
        return ch;
      } else {
        m[ch] -= 1;
      }
    }
    
    for (const auto& item : m) {
      if (item.second != 0) {
        return item.first;
      }
    }
  }

  char findTheDifference_2(string s, string t) {
    int num1 = 0, num2 = 0;
    for (const auto& ch : s) {
      num1 += ch;
    }

    for (const auto& ch : t) {
      num2 += ch;
    }

    return num2 - num1;
  }
};
